/*
 * Ported from @screeps/common lib/strongholds.js.
 * Copyright (c) 2016, Artem Chivchalov <contact@screeps.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted,
 * provided that the above copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THIS SOFTWARE.
 */

import * as C from '../constants.ts';

export type StrongholdTemplateName = keyof typeof templates;
export type StrongholdTemplate = (typeof templates)[StrongholdTemplateName];
export type StrongholdStructure = StrongholdTemplate['structures'][number];

export const templates = {
  bunker1: {
    description: 'Level 1 bunker-style Stronghold',
    rewardLevel: 1,
    structures: [
      { type: C.STRUCTURE_INVADER_CORE, dx: 0, dy: 0, level: 1, strongholdBehavior: 'bunker1' },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 1 },
      { type: C.STRUCTURE_CONTAINER, dx: 1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 0 },
    ],
  },
  bunker2: {
    description: 'Level 2 bunker-style Stronghold',
    rewardLevel: 2,
    structures: [
      { type: C.STRUCTURE_INVADER_CORE, dx: 0, dy: 0, level: 2, strongholdBehavior: 'bunker2' },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 0 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 1 },
      { type: C.STRUCTURE_CONTAINER, dx: 1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 0 },
      { type: C.STRUCTURE_CONTAINER, dx: -1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 0 },
    ],
  },
  bunker3: {
    description: 'Level 3 bunker-style Stronghold',
    rewardLevel: 3,
    structures: [
      { type: C.STRUCTURE_INVADER_CORE, dx: 0, dy: 0, level: 3, strongholdBehavior: 'bunker3' },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 0 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 2 },
      { type: C.STRUCTURE_CONTAINER, dx: 1, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -1 },
      { type: C.STRUCTURE_CONTAINER, dx: -2, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 0 },
      { type: C.STRUCTURE_CONTAINER, dx: 0, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 2 },
    ],
  },
  bunker4: {
    description: 'Level 4 bunker-style Stronghold',
    rewardLevel: 4,
    structures: [
      { type: C.STRUCTURE_INVADER_CORE, dx: 0, dy: 0, level: 4, strongholdBehavior: 'bunker4' },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 0 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 2 },
      { type: C.STRUCTURE_CONTAINER, dx: 2, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 0 },
      { type: C.STRUCTURE_CONTAINER, dx: -2, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 0 },
      { type: C.STRUCTURE_CONTAINER, dx: 0, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 2 },
      { type: C.STRUCTURE_CONTAINER, dx: 0, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -2 },
    ],
  },
  bunker5: {
    description: 'Level 5 bunker-style Stronghold',
    rewardLevel: 5,
    structures: [
      { type: C.STRUCTURE_INVADER_CORE, dx: 0, dy: 0, level: 5, strongholdBehavior: 'bunker5' },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 0 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -1 },
      { type: C.STRUCTURE_TOWER, dx: -1, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 1 },
      { type: C.STRUCTURE_TOWER, dx: 1, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -1 },
      { type: C.STRUCTURE_TOWER, dx: 0, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -2 },
      { type: C.STRUCTURE_TOWER, dx: 0, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: -3 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: -3 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: -3 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -3 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: -3 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -3 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: -3 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -3 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: -3 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: -3 },
      { type: C.STRUCTURE_ROAD, dx: -3, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: -3, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: 3, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 3, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: -3, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -3, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: 3, dy: -1 },
      { type: C.STRUCTURE_RAMPART, dx: 3, dy: -1 },
      { type: C.STRUCTURE_ROAD, dx: -3, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -3, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: 3, dy: 0 },
      { type: C.STRUCTURE_RAMPART, dx: 3, dy: 0 },
      { type: C.STRUCTURE_ROAD, dx: -3, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -3, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: 3, dy: 1 },
      { type: C.STRUCTURE_RAMPART, dx: 3, dy: 1 },
      { type: C.STRUCTURE_ROAD, dx: -3, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -3, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 3, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 3, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 3 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 3 },
      { type: C.STRUCTURE_ROAD, dx: -1, dy: 3 },
      { type: C.STRUCTURE_RAMPART, dx: -1, dy: 3 },
      { type: C.STRUCTURE_ROAD, dx: 0, dy: 3 },
      { type: C.STRUCTURE_RAMPART, dx: 0, dy: 3 },
      { type: C.STRUCTURE_ROAD, dx: 1, dy: 3 },
      { type: C.STRUCTURE_RAMPART, dx: 1, dy: 3 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 3 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 3 },
      { type: C.STRUCTURE_CONTAINER, dx: 2, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: 2 },
      { type: C.STRUCTURE_CONTAINER, dx: -2, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: -2 },
      { type: C.STRUCTURE_CONTAINER, dx: 2, dy: -2 },
      { type: C.STRUCTURE_ROAD, dx: 2, dy: -2 },
      { type: C.STRUCTURE_RAMPART, dx: 2, dy: -2 },
      { type: C.STRUCTURE_CONTAINER, dx: -2, dy: 2 },
      { type: C.STRUCTURE_ROAD, dx: -2, dy: 2 },
      { type: C.STRUCTURE_RAMPART, dx: -2, dy: 2 },
    ],
  },
} as const;

export const coreRewards = {
  [C.RESOURCE_SILICON]: [
    C.RESOURCE_WIRE,
    C.RESOURCE_SWITCH,
    C.RESOURCE_TRANSISTOR,
    C.RESOURCE_MICROCHIP,
    C.RESOURCE_CIRCUIT,
    C.RESOURCE_DEVICE,
  ],
  [C.RESOURCE_METAL]: [
    C.RESOURCE_ALLOY,
    C.RESOURCE_TUBE,
    C.RESOURCE_FIXTURES,
    C.RESOURCE_FRAME,
    C.RESOURCE_HYDRAULICS,
    C.RESOURCE_MACHINE,
  ],
  [C.RESOURCE_BIOMASS]: [
    C.RESOURCE_CELL,
    C.RESOURCE_PHLEGM,
    C.RESOURCE_TISSUE,
    C.RESOURCE_MUSCLE,
    C.RESOURCE_ORGANOID,
    C.RESOURCE_ORGANISM,
  ],
  [C.RESOURCE_MIST]: [
    C.RESOURCE_CONDENSATE,
    C.RESOURCE_CONCENTRATE,
    C.RESOURCE_EXTRACT,
    C.RESOURCE_SPIRIT,
    C.RESOURCE_EMANATION,
    C.RESOURCE_ESSENCE,
  ],
} as const;

export const coreAmounts = [0, 1000, 16000, 60000, 400000, 3000000] as const;

export const coreDensities = [10, 220, 1400, 5100, 14000, 31500] as const;

export const containerRewards = {
  [C.RESOURCE_UTRIUM_BAR]: 5,
  [C.RESOURCE_LEMERGIUM_BAR]: 5,
  [C.RESOURCE_ZYNTHIUM_BAR]: 5,
  [C.RESOURCE_KEANIUM_BAR]: 5,
  [C.RESOURCE_OXIDANT]: 5,
  [C.RESOURCE_REDUCTANT]: 5,
  [C.RESOURCE_PURIFIER]: 5,
  [C.RESOURCE_GHODIUM_MELT]: 20,
  [C.RESOURCE_BATTERY]: 10,
  [C.RESOURCE_COMPOSITE]: 10,
  [C.RESOURCE_CRYSTAL]: 15,
  [C.RESOURCE_LIQUID]: 30,
} as const;

export const containerAmounts = [0, 500, 4000, 10000, 50000, 360000] as const;
